name: employees_catalogue
description: Devskiller Flutter Employees Catalogue

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  mocktail: ^0.2.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.17.10
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
